name: CICD

on:
  push:
    branches: [ main ]
    
jobs:
  call_pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Webhook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_type: 'form-urlencoded'
        webhook_url: ${{ secrets.CICD_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        data: 'apiToken=${{ secrets.CICD_TOKEN }}'
